---
# Jupyter LLM docker compose by Matthew Printz

version: '3'
services:
  # Server-mode service
  beaker-server:
    user: root
    build:
      dockerfile: ${DOCKERFILE:-Dockerfile}
      context: .
    ports:
      - "8080:8888"
    environment:
      - JUPYTER_SERVER=http://beaker-server:8888
      - JUPYTER_BASE_URL=${JUPYTER_BASE_URL:-http://localhost:8080}
      - JUPYTER_TOKEN  # Only set in container if set in running environment
      - PYTHONPATH=/jupyter
      - ENABLE_CHECKPOINTS=true
      - TOOL_ENABLED_ASK_USER=true
      - TOOL_ENABLED_RUN_CODE=true
      - CONFIG_TYPE=server
      - LLM_PROVIDER_IMPORT_PATH=archytas.models.openai.OpenAIModel
      - LLM_SERVICE_MODEL=gpt-4o
      - LLM_SERVICE_TOKEN=${OPENAI_API_KEY}
    volumes:
      - ./beaker_kernel:/usr/local/share/jupyter/kernels/beaker_kernel
      - .:/jupyter
    command: [ "python3.10", "-m", "beaker_kernel.service.server", "--ip", "0.0.0.0" ]
