---
# Automatically build and publish

name: Build and Publish

# yamllint disable-line rule:truthy
on:
  push:
    tags: ['v*']

jobs:
    build-python:
        name: Build & Publish
        runs-on: ubuntu-22.04
        permissions:
            id-token: write
        steps:
            - name: Apt update and build install
              shell: bash
              run: |
                  sudo apt update || true
                  sudo apt install -y nodejs npm python3-pip || true
                  pip install hatch
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.workflow_run.head_branch }}

            - name: make build
              shell: bash
              run: |
                  make build

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1

    build-deploy-npm:
        name: Build & Publish
        runs-on: ubuntu-22.04
        permissions:
            id-token: write
        steps:
            - uses: actions/setup-node@v4
              with:
                node-version: '20.x'
                registry-url: 'https://registry.npmjs.org'
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.workflow_run.head_branch }}

            - name: npm build beaker-ts
              working-directory: beaker-ts
              shell: bash
              run: |
                npm ci
                npm run build
                npm publish --provenance --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: npm build beaker-vue
              working-directory: beaker-vue
              shell: bash
              run: |
                npm ci
                npm run build
                npm publish --provenance --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
