---
# Automatically build and publish

name: Build and Publish

# yamllint disable-line rule:truthy
on:
  push:
    tags: ['t[0-9]+**']

jobs:
    sanity-check:
        name: Sanity Check
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.workflow_run.head_branch }}
                fetch-depth: 0

            - name: Check Tag On main branch
              id: tag_on_main
              run: |
                  TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
                  BRANCH=$(git branch -r --contains $TAG_COMMIT | grep origin/main || true)
                  echo "branch_match=$BRANCH"
                  echo "branch_match=$BRANCH" >> $GITHUB_OUTPUT

            - name: Fail if tag is not on main
              if: steps.get_branch.outputs.branch_match == ''
              run: |
                  echo "Tag is not pointing to a commit on main. Exiting."
                  exit 1

    build-python:
        name: Build & Publish
        runs-on: ubuntu-22.04
        permissions:
            id-token: write
        needs: sanity-check
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.workflow_run.head_branch }}

            - name: Apt update and build install
              shell: bash
              run: |
                  sudo apt update || true
                  sudo apt install -y nodejs npm python3-pip || true
                  pip install hatch

            - name: make build
              shell: bash
              run: |
                  make build

            # - name: Publish package distributions to PyPI
            #   uses: pypa/gh-action-pypi-publish@release/v1

    build-deploy-npm:
        name: Build & Publish
        runs-on: ubuntu-22.04
        needs: sanity-check
        permissions:
            id-token: write
        steps:
            - uses: actions/setup-node@v4
              with:
                node-version: '20.x'
                registry-url: 'https://registry.npmjs.org'
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.workflow_run.head_branch }}

            - name: npm build beaker-ts
              working-directory: beaker-ts
              shell: bash
              run: |
                npm ci
                npm run build
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: npm build beaker-vue
              working-directory: beaker-vue
              shell: bash
              run: |
                npm ci
                npm run build
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
